/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ni.uni.edu.programacion.views.panels;

import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class PnlViewVehicles extends javax.swing.JPanel {

    public JButton getBtnBusqueda() {
        return btnBusqueda;
    }

    public JTable getTblTabla() {
        return tblTabla;
    }

    public JTextField getTxtBusqueda() {
        return txtBusqueda;
    }

    /**
     * Creates new form PnlViewVehicles
     */
    public PnlViewVehicles() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtBusqueda = new javax.swing.JTextField();
        btnBusqueda = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTabla = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Search by:");
        jPanel1.add(jLabel1);

        txtBusqueda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBusqueda.setPreferredSize(new java.awt.Dimension(170, 24));
        jPanel1.add(txtBusqueda);

        btnBusqueda.setText("Search");
        jPanel1.add(btnBusqueda);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        tblTabla.setBackground(new java.awt.Color(51, 255, 255));
        tblTabla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblTabla.setFont(new java.awt.Font("Consolas", 1, 11)); // NOI18N
        tblTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Stock Number", "Year", "Make", "Model", "Style", " VIN", "Exterior Color", "Interior Color", "Miles", "Price", "Transmission", "Engine", "Status", "Image"
            }
        ));
        tblTabla.setGridColor(new java.awt.Color(0, 0, 255));
        tblTabla.setSelectionForeground(new java.awt.Color(204, 204, 204));
        jScrollPane2.setViewportView(tblTabla);

        jPanel2.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBusqueda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblTabla;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables
}
