/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ni.uni.edu.programacion.views;

import java.awt.BorderLayout;
import javax.swing.JComponent;
import ni.uni.edu.programacion.Controllers.PnlViewVehicleController;
import ni.uni.edu.programacion.views.panels.PnlViewVehicle;

/**
 *
 * @author Javier Ramirez
 */
public class InternalFrmViewVehicles extends javax.swing.JInternalFrame {
    private PnlViewVehicle pnlViewVehicle;
    private PnlViewVehicleController pnlViewVehicleController;
    /**
     * Creates new form FrmViewVehicles
     */
    public InternalFrmViewVehicles() {
        initComponents();
        if(pnlViewVehicle == null){
            pnlViewVehicle = new PnlViewVehicle();
            pnlViewVehicleController = new PnlViewVehicleController(pnlViewVehicle);
        }
        
        addComponent(pnlViewVehicle);
        
        
        
    }
    
    
   private void addComponent(JComponent component) {
        pnlContentTable.removeAll();        
        pnlContentTable.add(component, BorderLayout.CENTER);
        pnlContentTable.setVisible(true);
        validate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        pnlContentTable = new javax.swing.JPanel();

        setBackground(new java.awt.Color(0, 204, 204));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("View Vehicles");

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));

        jButton1.setForeground(new java.awt.Color(0, 153, 51));
        jButton1.setText("New");
        jPanel3.add(jButton1);

        jButton2.setForeground(new java.awt.Color(204, 204, 0));
        jButton2.setText("Update");
        jPanel3.add(jButton2);

        jButton3.setForeground(new java.awt.Color(255, 0, 51));
        jButton3.setText("Delete");
        jPanel3.add(jButton3);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        pnlContentTable.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout pnlContentTableLayout = new javax.swing.GroupLayout(pnlContentTable);
        pnlContentTable.setLayout(pnlContentTableLayout);
        pnlContentTableLayout.setHorizontalGroup(
            pnlContentTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 497, Short.MAX_VALUE)
        );
        pnlContentTableLayout.setVerticalGroup(
            pnlContentTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 341, Short.MAX_VALUE)
        );

        getContentPane().add(pnlContentTable, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel pnlContentTable;
    // End of variables declaration//GEN-END:variables
}
