/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ni.uni.edu.programacion.views;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import ni.uni.edu.programacion.Controllers.PnlViewVehicleController;
import ni.uni.edu.programacion.component.model.VehicleTableModel;
import ni.uni.edu.programacion.views.panels.PnlVehicle;
import ni.uni.edu.programacion.views.panels.PnlViewVehicles;

/**
 *
 * @author Sistemas-05
 */
public class InternalFrmViewVehicles extends javax.swing.JInternalFrame {

    private PnlViewVehicles pnlViewVehicles;
    private PnlViewVehicleController pnlViewVehicleController;
    private VehicleTableModel tblViewModel;

    /**
     * Creates new form IFrmVehicle
     */
    public InternalFrmViewVehicles() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnNew = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        pnlContent = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Vehicles Catalog");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        jPanel1.add(btnNew);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        pnlContent.setBackground(new java.awt.Color(255, 255, 255));
        pnlContent.setLayout(new java.awt.BorderLayout());
        pnlViewVehicles = new PnlViewVehicles();
        pnlViewVehicleController = new PnlViewVehicleController(pnlViewVehicles);

        pnlContent.add(pnlViewVehicles, BorderLayout.CENTER);
        getContentPane().add(pnlContent, java.awt.BorderLayout.CENTER);

        setBounds(0, 0, 845, 548);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        jdVehicles jdV = new jdVehicles(null, true);
        jdV.addPropertySupport(pnlViewVehicleController.getTblViewModel());
        jdV.setVisible(true);
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            pnlViewVehicleController.actionPerformed(evt);
            pnlViewVehicleController.borrarDedata();
        } catch (IOException ex) {
            Logger.getLogger(InternalFrmViewVehicles.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        
        jdVehicles jdV = new jdVehicles(null, true);
        jdV.addPropertySupport(pnlViewVehicleController.getTblViewModel());
        jdV.setVisible(true);
        jdV.validacion();
        jdV.cargarDatos();
    }//GEN-LAST:event_btnUpdateActionPerformed

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlContent;
    // End of variables declaration//GEN-END:variables
}
